name: Flutter Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Generate coverage report
        run: |
          sudo apt-get install -y lcov
          genhtml -o coverage coverage/lcov.info

      - name: Generate Coverage Badge
        uses: dschinkel/coverage-badge-action@v1.1.0
        with:
          covfile: coverage/lcov.info
          outdir: coverage
          badgefile: coverage-badge.svg

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage