name: Flutter Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Generate coverage report
        run: |
          sudo apt-get install -y lcov
          genhtml -o coverage coverage/lcov.info

      - name: Debug Coverage Directory
        run: |
          echo "Listing contents of coverage directory..."
          ls -la coverage/
          echo "Checking coverage/index.html exists..."
          cat coverage/index.html || echo "Coverage report not generated!"

      - name: Generate Coverage Badge
        run: |
          COVERAGE_PERCENT=$(lcov --summary coverage/lcov.info | grep -Po '\d+\.\d+%' | head -1)
          echo "coverage=$COVERAGE_PERCENT" >> $GITHUB_ENV
          curl -o coverage/coverage-badge.svg "https://img.shields.io/badge/coverage-${{ env.coverage }}25-green"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage