name: Flutter Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Generate coverage report
        run: |
          sudo apt-get install -y lcov
          genhtml -o coverage coverage/lcov.info

      - name: Debug Coverage Directory
        run: |
          echo "Listing contents of coverage directory..."
          ls -la coverage/
          echo "Checking coverage/index.html exists..."
          cat coverage/index.html || echo "Coverage report not generated!"

      - name: Configure Git User
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Stash Uncommitted Changes
        run: |
          git stash --include-untracked

      - name: Fetch and Merge gh-pages Branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git merge origin/gh-pages --allow-unrelated-histories

      - name: Add Coverage Files
        run: |
          echo "Adding coverage files..."
          git add -f coverage/*

      - name: Commit Coverage Files
        run: |
          echo "Committing files..."
          git commit -m "Add coverage report"
          echo "Pushing to gh-pages branch..."
          git push origin gh-pages

      - name: Generate Coverage Badge
        run: |
          COVERAGE_PERCENT=$(lcov --summary coverage/lcov.info | grep -Po '\d+\.\d+%' | head -1)
          echo "Coverage percentage: $COVERAGE_PERCENT"
          ENCODED_COVERAGE_PERCENT=$(echo $COVERAGE_PERCENT | sed 's/%/%25/')
          echo "Encoded Coverage percentage: $ENCODED_COVERAGE_PERCENT"
          curl -o coverage/coverage-badge.svg "https://img.shields.io/badge/Coverage-${ENCODED_COVERAGE_PERCENT}-brightgreen.svg"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage

      - name: Restore Stash (If Needed)
        if: always()
        run: |
          git stash pop || echo "No stash to pop"